/*****
2.1
*****/
SELECT * FROM EMPLOYEE;
SELECT * FROM EMPLOYEE WHERE EMPLOYEE.LASTNAME = 'King';
SELECT * FROM EMPLOYEE WHERE EMPLOYEE.FIRSTNAME = 'Andrew' AND EMPLOYEE.REPORTSTO IS NULL;

/*****
2.2
*****/
SELECT * FROM ALBUM ORDER BY ALBUM.TITLE DESC;
SELECT FIRSTNAME FROM CUSTOMER ORDER BY CUSTOMER.CITY ASC;
/*****
2.3
*****/
INSERT INTO GENRE (GENREID,NAME) VALUES (26,'Indie');
INSERT INTO GENRE (GENREID,NAME) VALUES (27,'Dubstep');
INSERT INTO EMPLOYEE (EMPLOYEEID,LASTNAME,FIRSTNAME) VALUES (2000,'Omar','Guzman');
INSERT INTO EMPLOYEE (EMPLOYEEID,LASTNAME,FIRSTNAME) VALUES (2001,'O','G');
INSERT INTO CUSTOMER (CUSTOMERID,FIRSTNAME,LASTNAME,EMAIL) VALUES (2000,'Omar','Guzman','something@aol.com');
INSERT INTO CUSTOMER (CUSTOMERID,FIRSTNAME,LASTNAME,EMAIL) VALUES (2001,'Omar','Guzman','something@aol.com');
/*****
2.4
*****/
UPDATE CUSTOMER SET FIRSTNAME = 'Robert', LASTNAME = 'Walter' WHERE CUSTOMER.FIRSTNAME = 'Aaron' AND CUSTOMER.LASTNAME = 'Mitchell';
UPDATE ARTIST SET NAME = 'CCR' WHERE ARTIST.NAME = 'Creedence Clearwater Revival';
/*****
2.5
*****/
SELECT * FROM INVOICE WHERE INVOICE.BILLINGADDRESS LIKE 'T%';
/*****
2.6
*****/
SELECT * FROM INVOICE WHERE INVOICE.TOTAL BETWEEN 15 AND 50;
SELECT * FROM EMPLOYEE WHERE EMPLOYEE.HIREDATE BETWEEN '1-JUN-03' AND '1-MAR=2004';
/*****
2.7
*****/
DELETE FROM INVOICE WHERE INVOICE.CUSTOMERID = 32;
DELETE FROM CUSTOMER WHERE CUSTOMER.FIRSTNAME = 'Robert' AND CUSTOMER.LASTNAME = 'Walter';
/*****
3.1
*****/
SELECT TO_CHAR
    (SYSDATE, 'HH24:MI:SS') "NOW"
     FROM DUAL;
NOW;
/*****
7.1
*****/
